DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS
(
    ID           INTEGER          NOT NULL AUTO_INCREMENT,
    EMAIL        VARCHAR(255)     NOT NULL UNIQUE,
    NAME         VARCHAR(100)     NOT NULL,
    GRAVATAR_URL VARCHAR(255)     NOT NULL,
    PASSWORD     VARCHAR(255)     NOT NULL,
    USER_ROLE    VARCHAR(5) ARRAY NOT NULL DEFAULT ARRAY ['INFO'],
    ACTIVE       BOOLEAN          NOT NULL,
    PRIMARY KEY (ID)
);



