DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS
(
    ID           SERIAL           NOT NULL,
    EMAIL        VARCHAR(255)     NOT NULL UNIQUE,
    NAME         VARCHAR(100)     NOT NULL,
    GRAVATAR_URL VARCHAR(255)     NOT NULL,
    PASSWORD     VARCHAR(255)     NOT NULL,
    USER_ROLE    VARCHAR[]        NOT NULL,
    ACTIVE       BOOLEAN          NOT NULL,
    PRIMARY KEY (ID)
);